"""End-to-end ASR against a running muse server. Opt-in.

Requires:
- MUSE_REMOTE_SERVER set
- The target server has the whisper_model loaded
  (default whisper-tiny; override via MUSE_WHISPER_MODEL_ID)

These tests use a bundled audio fixture (tests/fixtures/asr_sample.wav,
generated by Kokoro TTS saying "The quick brown fox jumps over the
lazy dog.") so they don't depend on network access for the audio.
"""
from __future__ import annotations

from pathlib import Path

import pytest


pytestmark = pytest.mark.slow


FIXTURE = Path(__file__).parent.parent / "fixtures" / "asr_sample.wav"


def test_protocol_transcribes_sample_to_text(openai_client, whisper_model):
    """Upload the bundled sample and assert the transcript is non-empty."""
    if not FIXTURE.exists():
        pytest.skip(f"missing fixture: {FIXTURE}")

    with open(FIXTURE, "rb") as f:
        r = openai_client.audio.transcriptions.create(
            model=whisper_model, file=f,
        )
    assert r.text, f"empty transcription from {whisper_model}"
    # Sanity: known content of the fixture is "The quick brown fox..."
    # whisper-tiny may misspell or drop words; just check non-empty length
    assert len(r.text) > 5, (
        f"unexpectedly short transcription from {whisper_model}: {r.text!r}"
    )


def test_protocol_verbose_json_returns_segments(openai_client, whisper_model):
    """verbose_json must return language + segments + duration."""
    if not FIXTURE.exists():
        pytest.skip(f"missing fixture: {FIXTURE}")

    with open(FIXTURE, "rb") as f:
        r = openai_client.audio.transcriptions.create(
            model=whisper_model, file=f, response_format="verbose_json",
        )
    # OpenAI SDK returns a Verbose dict-like object
    assert hasattr(r, "language")
    assert hasattr(r, "segments")
    assert hasattr(r, "duration")
    assert r.duration > 0


def test_protocol_translate_endpoint_works(openai_client, whisper_model):
    """The translations endpoint must accept the same request shape."""
    if not FIXTURE.exists():
        pytest.skip(f"missing fixture: {FIXTURE}")

    with open(FIXTURE, "rb") as f:
        # The OpenAI SDK exposes audio.translations.create which hits
        # /v1/audio/translations. Source is English, so translation is
        # essentially a no-op transcription, but the protocol must work.
        r = openai_client.audio.translations.create(
            model=whisper_model, file=f,
        )
    assert r.text, f"empty translation from {whisper_model}"
