"""Protocol + dataclasses for image/ocr."""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Protocol, runtime_checkable


@dataclass
class OcrResult:
    """Output of an OCR call.

    text: extracted text. For Nougat-style models, this is LaTeX-flavored
    markdown; for TrOCR, plain text. The route does not interpret the
    string structure; it surfaces it as-is.

    completion_tokens: number of tokens generated by the decoder. Used
    for the response usage block (parity with chat completions).

    metadata: free-form dict the runtime may attach (e.g., generation
    config echo, post-processing flags). Optional.
    """

    text: str
    model_id: str
    completion_tokens: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)


@runtime_checkable
class OcrModel(Protocol):
    """Structural protocol any OCR backend satisfies.

    HFVision2SeqRuntime (the generic runtime) satisfies this without
    inheriting. Tests use fakes that match the signature structurally.
    """

    def ocr(
        self,
        image: Any,
        *,
        prompt: str | None = None,
        max_new_tokens: int = 512,
        num_beams: int = 1,
    ) -> OcrResult:
        """Extract text from a single image.

        `image` is a PIL.Image (the route layer decodes the multipart
        upload via the shared decode_image_file helper). `prompt` is
        an optional task hint forwarded to the processor; TrOCR ignores
        it, Nougat uses it. Returns one OcrResult.
        """
        ...
